name: Sample Deploy to GIT

on:
 workflow_dispatch:

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true"
            server-id: github
            java-version: 21
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}



# Do not forget to add  on  pom.xml the following section:
# <distributionManagement>
#     <repository>
#         <id>github</id>
#         <url>https://maven.pkg.github.com/netcracker/qubership-core-utils</url>
#     </repository>

# if you have couple module and want to skip module
# add plugin into pom.xml
# <plugin>
#     <groupId>org.apache.maven.plugins</groupId>
#     <artifactId>maven-deploy-plugin</artifactId>
#     <version>3.1.3</version>
#     <configuration>
#         <skip>false</skip>
#     </configuration>
# </plugin>
